language: java
jdk:
    - oraclejdk8
    - oraclejdk9
env:
    global:
        - EXAMPLE_DIR=testproject
        - ARCHETYPE_VERSION=1.1.0-SNAPSHOT
    matrix:
        - COMPILER_MODE=simple TEST_LIBRARY=none
        - COMPILER_MODE=test-only TEST_LIBRARY=none
        - COMPILER_MODE=retrolambda-main TEST_LIBRARY=none
        - COMPILER_MODE=retrolambda-all TEST_LIBRARY=none
        - TEST_LIBRARY=none COMPILER_MODE=simple
        - TEST_LIBRARY=junit COMPILER_MODE=simple
        - TEST_LIBRARY=testng COMPILER_MODE=simple
script:
    - mvn archetype:generate -B -DarchetypeGroupId=pl.org.miki -DarchetypeArtifactId=java8-quickstart-archetype -DarchetypeVersion=$ARCHETYPE_VERSION -DgroupId=com.example -DartifactId=$EXAMPLE_DIR -Dversion=1.0 -Dpackage=com.example.project -DcompilerMode=$COMPILER_MODE -DtestLibrary=$TEST_LIBRARY
    - test -f $EXAMPLE_DIR/pom.xml
